version: '3'
services:
  web:
    build: .
    volumes:
      - ./web:/var/www/html
    ports:
      - 8081:8081
      - 3000:3000
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5434:5432